package jp.co.webfrontier.training.worldclock;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */



import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.saxsys.mvvmfx.FluentViewLoader;
import de.saxsys.mvvmfx.ViewTuple;
import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import jp.co.webfrontier.training.worldclock.view.HelloWorldView;
import jp.co.webfrontier.training.worldclock.viewmodel.HelloWorldViewModel;

public class App extends Application {

    public static void main(String...args){
        App.launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        ViewTuple<HelloWorldView, HelloWorldViewModel> viewTuple = FluentViewLoader.fxmlView(HelloWorldView.class).load();

        Parent root = viewTuple.getView();
        stage.setScene(new Scene(root));
        stage.show();

        Logger logger = LoggerFactory.getLogger(App.class);

        ch.qos.logback.classic.Logger log = (ch.qos.logback.classic.Logger)logger;

        logger.debug("debug message");
    }
}